package com.arcsoft.arcfacedemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.arcsoft.arcfacedemo.dao.bean.PoliceFace;
import com.arcsoft.arcfacedemo.dao.bean.TerminalInformation;

import com.arcsoft.arcfacedemo.dao.PoliceFaceDao;
import com.arcsoft.arcfacedemo.dao.TerminalInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig policeFaceDaoConfig;
    private final DaoConfig terminalInformationDaoConfig;

    private final PoliceFaceDao policeFaceDao;
    private final TerminalInformationDao terminalInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        policeFaceDaoConfig = daoConfigMap.get(PoliceFaceDao.class).clone();
        policeFaceDaoConfig.initIdentityScope(type);

        terminalInformationDaoConfig = daoConfigMap.get(TerminalInformationDao.class).clone();
        terminalInformationDaoConfig.initIdentityScope(type);

        policeFaceDao = new PoliceFaceDao(policeFaceDaoConfig, this);
        terminalInformationDao = new TerminalInformationDao(terminalInformationDaoConfig, this);

        registerDao(PoliceFace.class, policeFaceDao);
        registerDao(TerminalInformation.class, terminalInformationDao);
    }
    
    public void clear() {
        policeFaceDaoConfig.clearIdentityScope();
        terminalInformationDaoConfig.clearIdentityScope();
    }

    public PoliceFaceDao getPoliceFaceDao() {
        return policeFaceDao;
    }

    public TerminalInformationDao getTerminalInformationDao() {
        return terminalInformationDao;
    }

}
