package com.arcsoft.arcfacedemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.arcsoft.arcfacedemo.dao.bean.CeWenInform;
import com.arcsoft.arcfacedemo.dao.bean.PoliceFace;
import com.arcsoft.arcfacedemo.dao.bean.PrisonerFace;
import com.arcsoft.arcfacedemo.dao.bean.TemperatureSetting;
import com.arcsoft.arcfacedemo.dao.bean.TerminalInformation;

import com.arcsoft.arcfacedemo.dao.CeWenInformDao;
import com.arcsoft.arcfacedemo.dao.PoliceFaceDao;
import com.arcsoft.arcfacedemo.dao.PrisonerFaceDao;
import com.arcsoft.arcfacedemo.dao.TemperatureSettingDao;
import com.arcsoft.arcfacedemo.dao.TerminalInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ceWenInformDaoConfig;
    private final DaoConfig policeFaceDaoConfig;
    private final DaoConfig prisonerFaceDaoConfig;
    private final DaoConfig temperatureSettingDaoConfig;
    private final DaoConfig terminalInformationDaoConfig;

    private final CeWenInformDao ceWenInformDao;
    private final PoliceFaceDao policeFaceDao;
    private final PrisonerFaceDao prisonerFaceDao;
    private final TemperatureSettingDao temperatureSettingDao;
    private final TerminalInformationDao terminalInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ceWenInformDaoConfig = daoConfigMap.get(CeWenInformDao.class).clone();
        ceWenInformDaoConfig.initIdentityScope(type);

        policeFaceDaoConfig = daoConfigMap.get(PoliceFaceDao.class).clone();
        policeFaceDaoConfig.initIdentityScope(type);

        prisonerFaceDaoConfig = daoConfigMap.get(PrisonerFaceDao.class).clone();
        prisonerFaceDaoConfig.initIdentityScope(type);

        temperatureSettingDaoConfig = daoConfigMap.get(TemperatureSettingDao.class).clone();
        temperatureSettingDaoConfig.initIdentityScope(type);

        terminalInformationDaoConfig = daoConfigMap.get(TerminalInformationDao.class).clone();
        terminalInformationDaoConfig.initIdentityScope(type);

        ceWenInformDao = new CeWenInformDao(ceWenInformDaoConfig, this);
        policeFaceDao = new PoliceFaceDao(policeFaceDaoConfig, this);
        prisonerFaceDao = new PrisonerFaceDao(prisonerFaceDaoConfig, this);
        temperatureSettingDao = new TemperatureSettingDao(temperatureSettingDaoConfig, this);
        terminalInformationDao = new TerminalInformationDao(terminalInformationDaoConfig, this);

        registerDao(CeWenInform.class, ceWenInformDao);
        registerDao(PoliceFace.class, policeFaceDao);
        registerDao(PrisonerFace.class, prisonerFaceDao);
        registerDao(TemperatureSetting.class, temperatureSettingDao);
        registerDao(TerminalInformation.class, terminalInformationDao);
    }
    
    public void clear() {
        ceWenInformDaoConfig.clearIdentityScope();
        policeFaceDaoConfig.clearIdentityScope();
        prisonerFaceDaoConfig.clearIdentityScope();
        temperatureSettingDaoConfig.clearIdentityScope();
        terminalInformationDaoConfig.clearIdentityScope();
    }

    public CeWenInformDao getCeWenInformDao() {
        return ceWenInformDao;
    }

    public PoliceFaceDao getPoliceFaceDao() {
        return policeFaceDao;
    }

    public PrisonerFaceDao getPrisonerFaceDao() {
        return prisonerFaceDao;
    }

    public TemperatureSettingDao getTemperatureSettingDao() {
        return temperatureSettingDao;
    }

    public TerminalInformationDao getTerminalInformationDao() {
        return terminalInformationDao;
    }

}
